### ISSUE TITLE
Adding New File Does Not Default to `root`

### ISSUE THREAD

**Issue by thejsj** [code-friends/CodeFriends#106]
![screen shot 2015-01-08 at 2 59 44 pm](https://cloud.githubusercontent.com/assets/1981198/5672633/0c300c84-9747-11e4-8ace-50d0e8364918.png)

1. Adding a new file should default to root. There should always be an option available
2. Since there would be default value, there should be a label on top of the field

**Comment by gladwearefriends** [comment]
this has been fixed to default to root. 
UI needs to be clear that it defaults to root however
