### ISSUE TITLE
When you got /#/home you are still emitting audio

### ISSUE THREAD

**Issue by thejsj** [code-friends/CodeFriends#152]
![screen shot 2015-01-16 at 2 10 29 pm](https://cloud.githubusercontent.com/assets/1981198/5785277/80244888-9d89-11e4-9a21-ade726632473.png)

Audio bar shows despite the fact I went to home view. 

Doug: Video element is removed, but media stream has not been disconnected.

**Comment by floofydoug** [comment]
The Audio tag shows up in chrome, but there wont be any audio playing if the user went to Project. IceComm severes the connection on close()
