### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by Xbot3maSter** [code-friends/CodeFriends#202]
Hello i am been so frustrated with the installation 
 I ll be really appreciate if someone can help me out .

This is the latest package i tried installing it with rethinkdb
here the command ;
```
 npm run dev

> CodeFriends@1.0.0 dev /root/Downloads/node-v0.12.7-linux-x64/bin/f3
> ./node_modules/nodemon/bin/nodemon.js --watch ./server server

28 Aug 07:21:58 - [nodemon] v1.4.1
28 Aug 07:21:58 - [nodemon] to restart at any time, enter `rs`
28 Aug 07:21:58 - [nodemon] watching: /root/Downloads/node-v0.12.7-linux-x64/bin/f3/server/**/*
28 Aug 07:21:58 - [nodemon] starting `node server`
config: { mysql: 
   { host: 'localhost',
     user: 'root',
     password: '',
     database: 'code_friends' },
  mongo: 'mongodb://127.0.0.1:27017/codeFriends?auto_reconnect',
  rethinkdb: { host: 'localhost', port: 28015, db: 'code_friends' },
  ports: { http: 8000, editor: 9000, chat: 9001, video: 8005 },
  url: '127.0.0.1',
  github: 
   { clientID: '364ea3bc2b086177fd27',
     clientSecret: '2dce4e81ad618474f5c822b4567200b941a6c1b1' },
  timeFormat: 'YYYY-MM-DDTHH:MM:SSZ',
  tmpDirectory: '../data/tmp',
  gitRepositoriesDirectory: '../data/git-repositories' }
Chat listening on port: 9001
Editor listening on port: 9000
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.listen (/root/Downloads/node-v0.12.7-linux-x64/bin/f3/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/root/Downloads/node-v0.12.7-linux-x64/bin/f3/server/index.js:43:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
28 Aug 07:22:04 - [nodemon] app crashed - waiting for file changes before starting...
```
How to resolve all them?

**Comment by Xbot3maSter** [comment]
In http://localhost:9000/ only show up 
Cannot GET /

**Comment by Xbot3maSter** [comment]
do i need configure knexfile.js this file?

**Comment by Xbot3maSter** [comment]
npm test

> CodeFriends@1.0.0 test /root/Downloads/CodeFriends-master
> export NODE_ENV='test'; ./node_modules/mocha/bin/mocha -t 15000 server/tests/index

config: { mysql: 
   { host: 'localhost',
     user: 'root',
     password: '',
     database: 'code_friends_test' },
  mongo: 'mongodb://localhost:27017/codeFriendsTest?auto_reconnect',
  rethinkdb: { host: 'localhost', port: 28015, db: 'code_friends_test' },
  ports: { http: 8000, editor: 9000, chat: 9001, video: 8005 },
  url: '127.0.0.1',
  github: 
   { clientID: '364ea3bc2b086177fd27',
     clientSecret: '2dce4e81ad618474f5c822b4567200b941a6c1b1' },
  timeFormat: 'YYYY-MM-DDTHH:MM:SSZ',
  tmpDirectory: '../data/tmp',
  gitRepositoriesDirectory: '../data/git-repositories' }
Chat listening on port: 9001
Editor listening on port: 9000


Server listening on port: 8000
  Code Friends
created table: users
created table: projects
created table: templates
created table: projects_users
    Database
      User
        ✓ should create a new user (344ms)
      Project
        ✓ should create a new project (59ms)
      Template
        ✓ should create a new template (98ms)
      User/Project
        ✓ should attach user to a project (198ms)
    Auth
      - should sign up the user
      - should authenticate the user
      - should logout the user
    API
      User
        ✓ should get all of the users and their projects on GET /user
        ✓ should get a specific user on GET /user/:username
        ✓ should create a new user on POST /user (355ms)
      Project
        ✓ should create a new project on POST /project (261ms)
        ✓ should add a user to a project on PUT /project/addUser (120ms)
        ✓ should get all of the user's projects on GET /project
        ✓ should get a specific project on GET /project/:projectName (101ms)
        ✓ should get a specific project on GET /project/:id (108ms)
        ✓ should delete a project on DELETE /project/projectId
        Uploading .zips in POST /api/project
Unhandled rejection ReqlRuntimeError: Index `v` was not found on table `code_friends_test.documents_ops` in:
r.table("documents_ops").orderBy({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "v"
    ^^^^^^^^^^
}).filter({
^^^^^^^^^^^
    name: "a4a7b92dd21e41a7c70d213d725c89ec088d7294274610fd681a43d12f417188"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).filter(function(var_1) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return var_1("v").ge(0).and(var_1("v").lt(1))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})
^^

    at Connection._processResponse (/root/Downloads/CodeFriends-master/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:184:35)
    at Socket.<anonymous> (/root/Downloads/CodeFriends-master/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:117:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
          1) should add all files in the main folder from a .zip with a parent directory
          ✓ should add all files in the main folder when uploading from .zip with no parent directory (1659ms)
        Cloning git repos through POST /api/project
          ✓ should add all files into a project when a git url (https) is passed to it (21548ms)
          - should add all files into a project when a git (git) url is passed to it
          - should add all files into a project when a larger git repo url is passed to it
      File
        ✓ should get the file structure for a project (1374ms)
        ✓ should add a new file when POSTed (94ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
Error Creating File or Folder: [TypeError: Cannot read property 'id' of undefined]
        ✓ should throw a 400 error when a file has already been created
        ✓ should add a new folder when POSTed (85ms)
        ✓ should add a new file to a folder that was already added (100ms)
        ✓ should add a new folder to a folder that was already added (100ms)
        ✓ should add a new file to a second-level folder (91ms)
        ✓ should get the file structure when requesting a project through GET
        ✓ should upload a new file to the database (267ms)
        ✓ should upload a new file to a folder in the database (342ms)
        ✓ should download a file in the database
        ✓ should download a file in the database that is not in the root folder
        ✓ should download a project on GET /api/project/download/:projectNameOrId (327ms)
        Moving Files
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from a folder to root on PUT /api/file/move (549ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from root to a folder on PUT /api/file/move (423ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from root to a folder that is within a folder on PUT /api/file/move (424ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from a folder that is within a folder to the root on PUT /api/file/move (391ms)
      Template
        ✓ should add a new template on POST api/template (73ms)
        ✓ should add a update a template name on PUT api/template/newName (58ms)
        ✓ should update a gitRepoUrl on PUT api/template/newGitRepoUrl (59ms)
        ✓ should get all templates on GET api/template/
        ✓ should delete a template on DELETE api/template/ (68ms)
Deleting All MySQL Tables
Deleting All RethinkDB Tables
Deleting Database Done


  37 passing (52s)
  5 pending
  1 failing

  1) Code Friends API Project Uploading .zips in POST /api/project should add all files in the main folder from a .zip with a parent directory:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  

npm ERR! Test failed.  See above for more details.

**Comment by thejsj** [comment]
Can you go to `localhost:8080/#dataexplorer` (while running RethinkDB and run the following command):

```
r.table("documents_ops").indexCreate('v')
```

Keep doing this until there are no more index errors :)

**Comment by thejsj** [comment]
For the other one, there's just some conflict with the ports. Try going into `config/default.js` (https://github.com/code-friends/CodeFriends/blob/master/config/default.js#L25-L28) until there are no more conflicts with the ports :). That's really all I can say. Again, you're probably running something in one of these ports. Keep in mind that ports 0-1000 are reserved.

**Comment by Xbot3maSter** [comment]
i had tried  keep run the command 

r.table("documents_ops").indexCreate('v')

here other problems again
npm test

> CodeFriends@1.0.0 test /root/Downloads/CodeFriends-master
> export NODE_ENV='test'; ./node_modules/mocha/bin/mocha -t 15000 server/tests/index

config: { mysql: 
   { host: 'localhost',
     user: 'root',
     password: '',
     database: 'code_friends_test' },
  mongo: 'mongodb://localhost:27017/codeFriendsTest?auto_reconnect',
  rethinkdb: { host: 'localhost', port: 28015, db: 'code_friends_test' },
  ports: { http: 8000, editor: 9000, chat: 9001, video: 8005 },
  url: '127.0.0.1',
  github: 
   { clientID: '364ea3bc2b086177fd27',
     clientSecret: '2dce4e81ad618474f5c822b4567200b941a6c1b1' },
  timeFormat: 'YYYY-MM-DDTHH:MM:SSZ',
  tmpDirectory: '../data/tmp',
  gitRepositoriesDirectory: '../data/git-repositories' }
Chat listening on port: 9001
Editor listening on port: 9000


  Code Friends
created table: users
created table: projects
created table: templates
created table: projects_users
    Database
      User
        ✓ should create a new user (968ms)
      Project
        ✓ should create a new project (193ms)
      Template
        ✓ should create a new template (128ms)
      User/Project
        ✓ should attach user to a project (408ms)
    Auth
      - should sign up the user
      - should authenticate the user
      - should logout the user
    API
      User
        ✓ should get all of the users and their projects on GET /user (54ms)
        ✓ should get a specific user on GET /user/:username
        ✓ should create a new user on POST /user (5712ms)
      Project
        ✓ should create a new project on POST /project (1021ms)
        ✓ should add a user to a project on PUT /project/addUser (465ms)
        ✓ should get all of the user's projects on GET /project (66ms)
        ✓ should get a specific project on GET /project/:projectName (418ms)
        ✓ should get a specific project on GET /project/:id (275ms)
        ✓ should delete a project on DELETE /project/projectId (58ms)
        Uploading .zips in POST /api/project
Unhandled rejection ReqlRuntimeError: Index `v` on table `code_friends_test.documents_ops` was accessed before its construction was finished in:
r.table("documents_ops").orderBy({
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "v"
    ^^^^^^^^^^
}).filter({
^^^^^^^^^^^
    name: "a4a7b92dd21e41a7c70d213d725c89ec088d7294274610fd681a43d12f417188"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
}).filter(function(var_1) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return var_1("v").ge(0).and(var_1("v").lt(1))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
})
^^

    at Connection._processResponse (/root/Downloads/CodeFriends-master/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:184:35)
    at Socket.<anonymous> (/root/Downloads/CodeFriends-master/node_modules/livedb-rethinkdb/node_modules/rethinkdbdash/lib/connection.js:117:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
          1) should add all files in the main folder from a .zip with a parent directory
          ✓ should add all files in the main folder when uploading from .zip with no parent directory (6602ms)
        Cloning git repos through POST /api/project
          ✓ should add all files into a project when a git url (https) is passed to it (15627ms)
          - should add all files into a project when a git (git) url is passed to it
          - should add all files into a project when a larger git repo url is passed to it
      File
        ✓ should get the file structure for a project (183ms)
        ✓ should add a new file when POSTed (186ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
Error Creating File or Folder: [TypeError: Cannot read property 'id' of undefined]
        ✓ should throw a 400 error when a file has already been created
        ✓ should add a new folder when POSTed (129ms)
        ✓ should add a new file to a folder that was already added (141ms)
        ✓ should add a new folder to a folder that was already added (173ms)
        ✓ should add a new file to a second-level folder (194ms)
        ✓ should get the file structure when requesting a project through GET (47ms)
        ✓ should upload a new file to the database (679ms)
        ✓ should upload a new file to a folder in the database (510ms)
        ✓ should download a file in the database
        ✓ should download a file in the database that is not in the root folder
        ✓ should download a project on GET /api/project/download/:projectNameOrId (783ms)
        Moving Files
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from a folder to root on PUT /api/file/move (1639ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from root to a folder on PUT /api/file/move (931ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from root to a folder that is within a folder on PUT /api/file/move (923ms)
Error creating new file or folder [Error: Path is Invalid or File Already Exists]
          ✓ should move a file from a folder that is within a folder to the root on PUT /api/file/move (708ms)
      Template
        ✓ should add a new template on POST api/template (199ms)
        ✓ should add a update a template name on PUT api/template/newName (138ms)
        ✓ should update a gitRepoUrl on PUT api/template/newGitRepoUrl (125ms)
        ✓ should get all templates on GET api/template/
        ✓ should delete a template on DELETE api/template/ (121ms)
Deleting All MySQL Tables
Deleting All RethinkDB Tables
Deleting Database Done


  37 passing (1m)
  5 pending
  1 failing

  1) Code Friends API Project Uploading .zips in POST /api/project should add all files in the main folder from a .zip with a parent directory:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  



npm ERR! Test failed.  See above for more details.

**Comment by thejsj** [comment]
The test is is telling you what's wrong. 

```
Unhandled rejection ReqlRuntimeError: Index `v` on table `code_friends_test.documents_ops` was accessed before its construction was finished in:
```

Basically, the index has not been created yet. 

The problem might be that you should add the index to the `rethinkdb.js` file: https://github.com/code-friends/CodeFriends/blob/master/server/rethinkdb.js#L7-L21. Read up on the [rethinkdb-init](https://www.npmjs.com/package/rethinkdb-init) module and how to add indexes.

**Comment by thejsj** [comment]
@Xbot3maSter This one seems to be resolved, right?

**Comment by b3lst** [comment]
this one issues  i just changed the versions and  it's worked  too.

**Comment by Xbot3maSter** [comment]
this one issue i just changed  the rethinkdb version match with package.json and it worked too

**Comment by thejsj** [comment]
Awesome. Closing then.
