### ISSUE TITLE
compilation with old package mongo

### ISSUE THREAD

**Issue by Xbot3maSter** [code-friends/CodeFriends#203]
Hello, due to rethinkdb only  support liinux  platform so i ve to  install the old  package with mongo database  run it on windows system .
 https://github.com/chaseme3/CodeFriends
i havent yet compiling sucess this project..
but here the errors again;
```
npm  test

> CodeFriends@1.0.0 test /root/Desktop/CodeFriends-master
> export NODE_ENV='test'; ./node_modules/mocha/bin/mocha server/tests/index

Deleting All Tables
editor listening on http://localhost:8007/
editor listening on http://localhost:8007/
Hello from Auth
got to projectRouter
/root/Desktop/CodeFriends-master/node_modules/express/lib/router/route.js:196
        throw new Error(msg);
              ^
Error: Route.post() requires callback functions but got a [object Undefined]
    at Route.(anonymous function) [as post] (/root/Desktop/CodeFriends-master/node_modules/express/lib/router/route.js:196:15)
    at Function.proto.(anonymous function) (/root/Desktop/CodeFriends-master/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/root/Desktop/CodeFriends-master/server/project/projectRoutes.js:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/Desktop/CodeFriends-master/server/api.js:2:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/Desktop/CodeFriends-master/server/index.js:83:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/Desktop/CodeFriends-master/server/tests/integration.js:5:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/root/Desktop/CodeFriends-master/server/tests/index.js:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /root/Desktop/CodeFriends-master/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (/root/Desktop/CodeFriends-master/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (/root/Desktop/CodeFriends-master/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (/root/Desktop/CodeFriends-master/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Test failed.  See above for more details.
```
how to fix it.?

**Comment by Xbot3maSter** [comment]
during my dependencies building output;

npm install 
npm WARN package.json Dependency 'mysql' exists in both dependencies and devDependencies, using 'mysql@^2.5.4' from dependencies
npm WARN peerDependencies The peer dependency mongodb@~1.4 included from mongoskin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> ws@0.6.5 install /root/Desktop/cod3/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Desktop/cod3/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/root/Desktop/cod3/node_modules/ws/build'
 
> hiredis@0.2.0 install /root/Desktop/cod3/node_modules/livedb/node_modules/hiredis
> node-gyp rebuild

make: Entering directory '/root/Desktop/cod3/node_modules/livedb/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis.a
  COPY Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory '/root/Desktop/cod3/node_modules/livedb/node_modules/hiredis/build'
 
> kerberos@0.0.11 install /root/Desktop/cod3/node_modules/livedb-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Desktop/cod3/node_modules/livedb-mongo/node_modules/mongodb/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
kerberos.target.mk:91: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: Leaving directory '/root/Desktop/cod3/node_modules/livedb-mongo/node_modules/mongodb/node_modules/kerberos/build'
 
> hiredis@0.2.0 install /root/Desktop/cod3/node_modules/share/node_modules/livedb/node_modules/hiredis
> node-gyp rebuild

make: Entering directory '/root/Desktop/cod3/node_modules/share/node_modules/livedb/node_modules/hiredis/build'
  CC(target) Release/obj.target/hiredis/deps/hiredis/hiredis.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/net.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/sds.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/async.o
  CC(target) Release/obj.target/hiredis/deps/hiredis/read.o
  AR(target) Release/obj.target/deps/hiredis.a
  COPY Release/hiredis.a
  CXX(target) Release/obj.target/hiredis/src/hiredis.o
  CXX(target) Release/obj.target/hiredis/src/reader.o
  SOLINK_MODULE(target) Release/obj.target/hiredis.node
  COPY Release/hiredis.node
make: Leaving directory '/root/Desktop/cod3/node_modules/share/node_modules/livedb/node_modules/hiredis/build'

> kerberos@0.0.4 install /root/Desktop/cod3/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Desktop/cod3/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/root/Desktop/cod3/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/build'

> bson@0.1.8 install /root/Desktop/cod3/node_modules/mongo-client/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Desktop/cod3/node_modules/mongo-client/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
bson.target.mk:83: recipe for target 'Release/obj.target/bson/ext/bson.o' failed
make: Leaving directory '/root/Desktop/cod3/node_modules/mongo-client/node_modules/mongodb/node_modules/bson/build'

> bson@0.2.22 install /root/Desktop/cod3/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Desktop/cod3/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory '/root/Desktop/cod3/node_modules/mongoose/node_modules/mongodb/node_modules/bson/build'

> bson@0.2.22 install /root/Desktop/cod3/node_modules/livedb-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/root/Desktop/cod3/node_modules/livedb-mongo/node_modules/mongodb/node_modules/bson/build'
  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/obj.target/bson.node
  COPY Release/bson.node
make: Leaving directory '/root/Desktop/cod3/node_modules/livedb-mongo/node_modules/mongodb/node_modules/bson/build'
path@0.4.10 node_modules/path

share-codemirror@0.1.0 node_modules/share-codemirror

marked@0.3.5 node_modules/marked

cookie-parser@1.3.5 node_modules/cookie-parser
├── cookie@0.1.3
└── cookie-signature@1.0.6

stream@0.0.2 node_modules/stream
└── emitter-component@1.1.1

passport@0.2.2 node_modules/passport
├── pause@0.0.1
└── passport-strategy@1.0.0

morgan@1.6.1 node_modules/morgan
├── basic-auth@1.0.3
├── on-headers@1.0.0
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
└── debug@2.2.0 (ms@0.7.1)

express-session@1.11.3 node_modules/express-session
├── cookie@0.1.3
├── cookie-signature@1.0.6
├── utils-merge@1.0.0
├── on-headers@1.0.0
├── parseurl@1.3.0
├── depd@1.0.1
├── crc@3.3.0
├── uid-safe@2.0.0 (base64-url@1.2.1)
└── debug@2.2.0 (ms@0.7.1)

optimist@0.6.1 node_modules/optimist
├── wordwrap@0.0.3
└── minimist@0.0.10

connect@3.4.0 node_modules/connect
├── utils-merge@1.0.0
├── parseurl@1.3.0
├── debug@2.2.0 (ms@0.7.1)
└── finalhandler@0.4.0 (escape-html@1.0.2, unpipe@1.0.0, on-finished@2.3.0)

passport-github@0.1.5 node_modules/passport-github
├── pkginfo@0.2.3
└── passport-oauth@0.1.15 (passport@0.1.18, oauth@0.9.13)

body-parser@1.13.3 node_modules/body-parser
├── bytes@2.1.0
├── content-type@1.0.1
├── depd@1.0.1
├── on-finished@2.3.0 (ee-first@1.1.1)
├── qs@4.0.0
├── raw-body@2.1.2 (unpipe@1.0.0)
├── http-errors@1.3.1 (inherits@2.0.1, statuses@1.2.1)
├── debug@2.2.0 (ms@0.7.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── iconv-lite@0.4.11

bluebird@2.9.34 node_modules/bluebird

chai@1.10.0 node_modules/chai
├── assertion-error@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

express@4.13.3 node_modules/express
├── escape-html@1.0.2
├── array-flatten@1.1.1
├── merge-descriptors@1.0.0
├── cookie@0.1.3
├── utils-merge@1.0.0
├── cookie-signature@1.0.6
├── methods@1.1.1
├── fresh@0.3.0
├── range-parser@1.0.2
├── vary@1.0.1
├── path-to-regexp@0.1.7
├── content-type@1.0.1
├── etag@1.7.0
├── parseurl@1.3.0
├── content-disposition@0.5.0
├── serve-static@1.10.0
├── depd@1.0.1
├── finalhandler@0.4.0 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── qs@4.0.0
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.8 (forwarded@0.1.0, ipaddr.js@1.0.1)
├── send@0.13.0 (destroy@1.0.3, statuses@1.2.1, ms@0.7.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.8 (media-typer@0.3.0, mime-types@2.1.6)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.6)

should@4.6.5 node_modules/should
├── should-type@0.0.4
├── should-equal@0.3.1
└── should-format@0.0.7

supertest@0.15.0 node_modules/supertest
├── methods@1.1.1
└── superagent@0.21.0 (extend@1.2.1, methods@1.0.1, cookiejar@2.0.1, component-emitter@1.1.2, reduce-component@1.0.1, qs@1.2.0, mime@1.2.11, debug@2.2.0, readable-stream@1.0.27-1, form-data@0.1.3, formidable@1.0.14)

ws@0.6.5 node_modules/ws
├── options@0.0.6
├── ultron@1.0.2
└── nan@1.4.3

mysql@2.9.0 node_modules/mysql
├── bignumber.js@2.0.7
└── readable-stream@1.1.13 (isarray@0.0.1, inherits@2.0.1, string_decoder@0.10.31, core-util-is@1.0.1)

lodash@2.4.2 node_modules/lodash

request@2.61.0 node_modules/request
├── aws-sign2@0.5.0
├── forever-agent@0.6.1
├── caseless@0.11.0
├── stringstream@0.0.4
├── tunnel-agent@0.4.1
├── oauth-sign@0.8.0
├── isstream@0.1.2
├── json-stringify-safe@5.0.1
├── extend@3.0.0
├── node-uuid@1.4.3
├── qs@4.0.0
├── combined-stream@1.0.5 (delayed-stream@1.0.0)
├── form-data@1.0.0-rc3 (async@1.4.2)
├── mime-types@2.1.6 (mime-db@1.18.0)
├── http-signature@0.11.0 (assert-plus@0.1.5, asn1@0.1.11, ctype@0.5.3)
├── bl@1.0.0 (readable-stream@2.0.2)
├── tough-cookie@2.0.0
├── har-validator@1.8.0 (commander@2.8.1, chalk@1.1.1, is-my-json-valid@2.12.2)
└── hawk@3.1.0 (cryptiles@2.0.4, sntp@1.0.9, boom@2.8.0, hoek@2.14.0)

gulp@3.9.0 node_modules/gulp
├── pretty-hrtime@1.0.0
├── interpret@0.6.5
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.0 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, strip-ansi@3.0.0, has-ansi@2.0.0)
├── semver@4.3.6
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.1.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.2.1)
├── gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, beeper@1.1.0, object-assign@3.0.0, replace-ext@0.0.1, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.8, strip-bom@1.0.0, defaults@1.0.2, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)

livedb@0.4.13 node_modules/livedb
├── arraydiff@0.1.1
├── deep-is@0.1.3
├── ot-text-tp2@1.0.0
├── ot-text@1.0.1
├── async@0.7.0
├── statsd-client@0.2.0
├── ot-json0@1.0.1
├── redis@0.12.1
└── hiredis@0.2.0 (bindings@1.2.1, nan@1.5.3)

bookshelf@0.7.9 node_modules/bookshelf
├── inherits@2.0.1
├── trigger-then@0.3.0
├── simple-extend@0.1.0
├── create-error@0.3.1
├── inflection@1.7.1
├── semver@4.3.6
└── backbone@1.1.0 (underscore@1.8.3)

mocha@2.3.1 node_modules/mocha
├── escape-string-regexp@1.0.2
├── supports-color@1.2.0
├── growl@1.8.1
├── commander@2.3.0
├── diff@1.4.0
├── debug@2.0.0 (ms@0.6.2)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── glob@3.2.3 (inherits@2.0.1, graceful-fs@2.0.3, minimatch@0.2.14)
├── lodash.create@3.1.1 (lodash._isiterateecall@3.0.9, lodash._basecreate@3.0.3, lodash._baseassign@3.2.0)
└── jade@1.11.0 (character-parser@1.2.1, void-elements@2.0.1, commander@2.6.0, jstransformer@0.0.2, constantinople@3.0.2, with@4.0.3, clean-css@3.4.1, uglify-js@2.4.24, transformers@2.1.0)

moment@2.10.6 node_modules/moment

codemirror@4.13.0 node_modules/codemirror

knex@0.7.6 node_modules/knex
├── inherits@2.0.1
├── interpret@0.3.10
├── generic-pool-redux@0.1.0
├── minimist@1.1.3
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── tildify@1.0.0 (user-home@1.1.1)
├── readable-stream@1.1.13 (isarray@0.0.1, string_decoder@0.10.31, core-util-is@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
└── liftoff@0.13.6 (extend@1.3.0, flagged-respawn@0.3.1, resolve@1.0.0, findup-sync@0.1.3)

share@0.7.40 node_modules/share
├── ot-text-tp2@1.0.0
├── hat@0.0.3
├── ot-text@1.0.1
├── ot-json0@1.0.1
├── async@0.9.2
├── express@3.21.2 (escape-html@1.0.2, merge-descriptors@1.0.0, cookie@0.1.3, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, utils-merge@1.0.0, range-parser@1.0.2, basic-auth@1.0.3, vary@1.0.1, etag@1.7.0, content-type@1.0.1, parseurl@1.3.0, content-disposition@0.5.0, commander@2.6.0, depd@1.0.1, debug@2.2.0, mkdirp@0.5.1, proxy-addr@1.0.8, send@0.13.0, connect@2.30.2)
└── livedb@0.5.13 (arraydiff@0.1.1, deep-is@0.1.3, statsd-client@0.2.0, redis@0.12.1, hiredis@0.2.0)

mongo-client@0.2.1 node_modules/mongo-client
├── reducible@1.0.6 (method@2.0.0)
├── callback-reduce@1.1.0 (functional@1.0.0, reducible@1.0.6)
├── reducers@3.0.0-alpha (reducible@1.0.6)
├── cache-reduce@0.1.1 (reducible@1.0.6, buffer-reduce@0.1.0)
└── mongodb@1.2.14 (bson@0.1.8)

mongoose@3.9.7 node_modules/mongoose
├── regexp-clone@0.0.1
├── kareem@0.0.4
├── sliced@0.0.5
├── muri@0.3.1
├── mpromise@0.5.4
├── hooks@0.3.2
├── mpath@0.1.1
├── async@0.9.0
├── ms@0.1.0
├── mquery@1.0.0 (debug@0.7.4)
└── mongodb@1.4.12 (readable-stream@2.0.2, kerberos@0.0.4, bson@0.2.22)

livedb-mongo@0.4.1 node_modules/livedb-mongo
├── async@0.9.2
├── mongodb@1.4.39 (readable-stream@2.0.2, kerberos@0.0.11, bson@0.2.22)
└── mongoskin@1.4.13

**Comment by thejsj** [comment]
I'm sorry, but I really can't help you out with trying to run the Mongo version. It seems that you just grabbed some random commit that was probably not even working to begin with. I'd recommend running [vagrant](https://www.vagrantup.com/) on your Windows machine and running RethinkDB from there. There's some tutorials online on how to setup RethinkDB on Vagrant. 

Closing this since, again, we can't really support MongoDB and RethinkDB at the same time.
